name: demo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.7
  hooks_riverpod: ^2.3.8
  riverpod_annotation: ^2.1.2
  riverpod_generator: ^2.2.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.4.1
  json_serializable: ^6.6.2
flutter:
  uses-material-design: true
  assets:
    - images/monster.png
